language: php

sudo: false

php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

notifications:
    email: deploy@peter-gribanov.ru

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit

after_script:
    - ls -la
    - ls -la build/logs
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
    - ls -la build/logs
    - vendor/bin/coveralls -v -c .coveralls.yml
